[CN-649] Change nightly test triggers (#515)

diff --git a/.github/workflows/e2e-eks.yaml b/.github/workflows/e2e-eks.yaml
--- a/.github/workflows/e2e-eks.yaml
+++ b/.github/workflows/e2e-eks.yaml
@@ -1,34 +1,51 @@
-name: Nightly E2E tests on Azure
+name: E2E tests on AWS
 on:
   workflow_dispatch:
-  schedule:
-    - cron: "0 9 * * *"
+  workflow_call:
+
 
 env:
-  AZURE_RESOURCE_GROUP: operator-test
-  NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}
+  AWS_REGION: us-east-1
+
 jobs:
   prepare-env:
-    name: Create AKS cluster
+    name: Create EKS cluster
     runs-on: ubuntu-latest
     outputs:
       CLUSTER_NAME: ${{ steps.create-cluster.outputs.CLUSTER_NAME }}
     steps:
-      - name: Azure login
-        uses: azure/login@v1
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v1
         with:
-          creds: ${{ secrets.AZURE_CREDENTIALS }}
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ env.AWS_REGION }}
 
-      - name: Create AKS cluster
+      - name: Install eksctl
+        run: |-
+          curl --silent --location \
+            "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" \
+            | tar xz -C /tmp
+          sudo mv /tmp/eksctl /usr/local/bin
+
+      - name: Create EKS cluster
         id: create-cluster
-        uses: azure/CLI@v1
-        with:
-          azcliversion: 2.31.0
-          inlineScript: |
-            CLUSTER_NAME="operator-e2e-test-${GITHUB_SHA::8}-${{ github.run_number }}"
-            echo "CLUSTER_NAME=${CLUSTER_NAME}" >> $GITHUB_OUTPUT
-            az aks create --resource-group ${AZURE_RESOURCE_GROUP} --name "${CLUSTER_NAME}" \
-              --node-count 3 --generate-ssh-keys
+        run: |-
+          CLUSTER_NAME="operator-e2e-test-${GITHUB_SHA::8}-${{ github.run_number }}"
+          echo "CLUSTER_NAME=${CLUSTER_NAME}" >> $GITHUB_OUTPUT
+          eksctl create cluster --name "${CLUSTER_NAME}" \
+            --zones ${AWS_REGION}a \
+            --zones ${AWS_REGION}c \
+            --with-oidc \
+            --without-nodegroup
+
+          eksctl create nodegroup --cluster "${CLUSTER_NAME}" \
+            --name node-group-1 \
+            --node-type t3.medium \
+            --nodes 3 \
+            --managed
+
+          eksctl create addon --name aws-ebs-csi-driver --cluster "${CLUSTER_NAME}"
 
   new-relic-setup:
     name: Setup New Relic agent
@@ -41,14 +58,16 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v3
 
-      - name: Azure login
-        uses: azure/login@v1
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v1
         with:
-          creds: ${{ secrets.AZURE_CREDENTIALS }}
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ env.AWS_REGION }}
 
       - name: Update kubeconfig
         run: |-
-          az aks get-credentials --resource-group "${AZURE_RESOURCE_GROUP}" --name "${{ env.CLUSTER_NAME }}"
+          aws eks update-kubeconfig --name "${{ env.CLUSTER_NAME }}"
 
       - name: Install New Relic repo
         run: |
@@ -56,15 +75,15 @@ jobs:
 
       - name: Install New Relic agent
         run: |
+          CLUSTER_NAME="operator-e2e-test-${GITHUB_SHA::8}-${{ github.run_number }}"
           kubectl create namespace newrelic
           helm install --namespace=newrelic newrelic-bundle -f .github/newrelic/newrelic-values.yaml \
-            --set "global.cluster=azure-operator" \
+            --set "global.cluster=aws-operator" \
             --set "global.licenseKey=${{ secrets.NEW_RELIC_LICENCE_KEY }}" \
             --set "newrelic-logging.fluentBit.additionalEnvVariables[0].name=K_CLUSTER_NAME,newrelic-logging.fluentBit.additionalEnvVariables[0].value=${{ env.CLUSTER_NAME }}" \
             --set "newrelic-logging.fluentBit.additionalEnvVariables[1].name=GITHUB_RUN_ID,newrelic-logging.fluentBit.additionalEnvVariables[1].value=\"${{ github.run_id }}\"" \
             --set "newrelic-logging.fluentBit.additionalEnvVariables[2].name=GITHUB_RUN_NUMBER,newrelic-logging.fluentBit.additionalEnvVariables[2].value=\"${{ github.run_number }}\"" \
             --set "newrelic-logging.fluentBit.additionalEnvVariables[3].name=GITHUB_SHA,newrelic-logging.fluentBit.additionalEnvVariables[3].value=${{ github.sha }}" \
-            --set "newrelic-logging.fluentBit.additionalEnvVariables[4].name=LOG_PARSER,newrelic-logging.fluentBit.additionalEnvVariables[4].value=cri" \
             newrelic/nri-bundle
 
   get-image:
@@ -79,18 +98,13 @@ jobs:
       - name: Build and push image to ttl.sh
         id: build-img
         run: |
-          if [[ "${{github.event_name}}" == "workflow_dispatch" ]]; then
-            IMG=ttl.sh/$(uuidgen):2h
-            echo "IMG=${IMG}" >> $GITHUB_OUTPUT
-            make docker-build-ci IMG=$IMG VERSION=${{github.sha}}
-            make docker-push IMG=$IMG
-          else
-            IMG=hazelcast/hazelcast-platform-operator:latest-snapshot
-            echo "IMG=${IMG}" >> $GITHUB_OUTPUT
-          fi
+          IMG=ttl.sh/$(uuidgen):2h
+          echo "IMG=${IMG}" >> $GITHUB_OUTPUT
+          make docker-build-ci IMG=$IMG VERSION=${{github.sha}}
+          make docker-push IMG=$IMG
 
-  aks-e2e-tests:
-    name: Run e2e test on AKS
+  eks-e2e-tests:
+    name: Run e2e test on EKS
     runs-on: ubuntu-latest
     needs: ["prepare-env", "new-relic-setup", "get-image"]
     defaults:
@@ -101,9 +115,9 @@ jobs:
       matrix:
         edition: ["os", "ee"]
     env:
-      NAMESPACE: test-operator-nightly-${{ matrix.edition }}
-      IMG: ${{ needs.get-image.outputs.IMG }}
+      NAMESPACE: test-operator-${{ matrix.edition }}
       NAME_PREFIX: hp-${{ matrix.edition }}-${{ github.run_id }}-
+      IMG: ${{ needs.get-image.outputs.IMG }}
     steps:
       - name: Checkout
         uses: actions/checkout@v3
@@ -122,15 +136,17 @@ jobs:
           restore-keys: |
             ${{ runner.os }}-go-
 
-      - name: Azure login
-        uses: azure/login@v1
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v1
         with:
-          creds: ${{ secrets.AZURE_CREDENTIALS }}
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ env.AWS_REGION }}
 
       - name: Update kubeconfig
         run: |-
           CLUSTER_NAME="operator-e2e-test-${GITHUB_SHA::8}-${{ github.run_number }}"
-          az aks get-credentials --resource-group "${AZURE_RESOURCE_GROUP}" --name "${CLUSTER_NAME}"
+          aws eks update-kubeconfig --name "${CLUSTER_NAME}"
 
       - name: Deploy Operator to EKS
         run: |
@@ -138,15 +154,16 @@ jobs:
           kubectl label namespace ${NAMESPACE} newrelic.com/scrape=true
           kubectl config set-context --current --namespace=${NAMESPACE}
 
-          make deploy NAMESPACE=${NAMESPACE} IMG=${IMG} NAME_PREFIX=${NAME_PREFIX}
           DEPLOY_NAME=${NAME_PREFIX}controller-manager
+
+          make deploy NAMESPACE=${NAMESPACE} IMG=${IMG} NAME_PREFIX=${NAME_PREFIX}
           kubectl rollout status deployment $DEPLOY_NAME
 
       - name: Create secrets
         if: matrix.edition == 'ee'
         run: |
-          kubectl create secret generic hazelcast-license-key --namespace ${NAMESPACE} \
-            --from-literal=license-key=${{ secrets.HZ_LICENSE_KEY }}
+          kubectl create secret generic hazelcast-license-key \
+            --namespace ${NAMESPACE} --from-literal=license-key=${{ secrets.HZ_LICENSE_KEY }}
 
           kubectl create secret generic br-secret-s3 --namespace ${NAMESPACE} \
             --from-literal=region=us-east-1 \
@@ -169,7 +186,7 @@ jobs:
             ee) GO_TEST_FLAGS=-ee=true;;
             *)  echo Unexpected edition: ${{ matrix.edition }} && exit 1;;
           esac
-          make test-e2e GO_TEST_FLAGS=${GO_TEST_FLAGS} NAMESPACE=${NAMESPACE} NAME_PREFIX=${NAME_PREFIX} WORKFLOW_ID=aks
+          make test-e2e GO_TEST_FLAGS=${GO_TEST_FLAGS} NAMESPACE=${NAMESPACE} NAME_PREFIX=${NAME_PREFIX} WORKFLOW_ID=eks
 
       - name: Clean up after Tests
         if: always()
@@ -180,40 +197,48 @@ jobs:
         if: always()
         uses: actions/upload-artifact@v3
         with:
-          name: test-report
-          path: allure-results/aks/
+          name: test-report-eks
+          path: allure-results/eks/
 
   report-generation:
-    needs: ["prepare-env", "aks-e2e-tests"]
-    if: always() && (needs.aks-e2e-tests.result == 'success' || needs.aks-e2e-tests.result == 'failure')
+    needs: ["prepare-env", "eks-e2e-tests"]
+    if: always() && (needs.eks-e2e-tests.result == 'success' || needs.eks-e2e-tests.result == 'failure')
     uses: ./.github/workflows/generate-test-report.yaml
     secrets: inherit
     with:
-      WORKFLOW_ID: aks
+      WORKFLOW_ID: eks
 
   delete-cluster:
-    name: Delete AKS cluster
+    name: Delete EKS cluster
     runs-on: ubuntu-latest
     if: always()
-    needs: ["prepare-env", "aks-e2e-tests"]
+    needs: ["prepare-env", "eks-e2e-tests"]
     steps:
-      - name: Azure login
-        uses: azure/login@v1
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v1
         with:
-          creds: ${{ secrets.AZURE_CREDENTIALS }}
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ env.AWS_REGION }}
 
-      - name: Delete AKS cluster
-        uses: azure/CLI@v1
-        with:
-          azcliversion: 2.31.0
-          inlineScript: |
-            CLUSTER_NAME="operator-e2e-test-${GITHUB_SHA::8}-${{ github.run_number }}"
-            az aks delete --name "${CLUSTER_NAME}" --resource-group "${AZURE_RESOURCE_GROUP}" -y
+      - name: Install eksctl
+        run: |-
+          curl --silent --location \
+            "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" \
+            | tar xz -C /tmp
+          sudo mv /tmp/eksctl /usr/local/bin
+
+      - name: Delete EKS cluster
+        run: |-
+          CLUSTER_NAME="operator-e2e-test-${GITHUB_SHA::8}-${{ github.run_number }}"
+          eksctl delete addon --name aws-ebs-csi-driver --cluster "${CLUSTER_NAME}" || echo "could not delete addon"
+          eksctl delete nodegroup --cluster "${CLUSTER_NAME}" --name node-group-1
+          eksctl delete cluster "${CLUSTER_NAME}" --wait
 
   slack_notify:
     name: Slack Notify
-    needs: ["aks-e2e-tests", "delete-cluster"]
-    if: always() && ( needs.aks-e2e-tests.result != 'success' || needs.delete-cluster.result != 'success')
+    needs: ["eks-e2e-tests", "delete-cluster"]
+    if: always() && ( needs.eks-e2e-tests.result != 'success' || needs.delete-cluster.result != 'success')
     runs-on: ubuntu-latest
     steps:
       - uses: 8398a7/action-slack@a189acbf0b7ea434558662ae25a0de71df69a435
