Add linter phase to workflow (#77)
* Run `golangci-lint` and `yamllint`

diff --git a/.github/workflows/nightly-e2e-gke.yaml b/.github/workflows/nightly-e2e-gke.yaml
--- a/.github/workflows/nightly-e2e-gke.yaml
+++ b/.github/workflows/nightly-e2e-gke.yaml
@@ -14,7 +14,7 @@ jobs:
     runs-on: ubuntu-20.04
     outputs:
       CLUSTER_NAME: ${{ steps.set-cluster-name.outputs.CLUSTER_NAME }}
-    env:  
+    env:
       GCP_NETWORK: operator-test-network
     steps:
       - name: Set up Cloud SDK
@@ -29,13 +29,18 @@ jobs:
         run: |-
           CLUSTER_NAME="operator-e2e-test-${GITHUB_SHA::8}-${GITHUB_RUN_NUMBER}"
           echo "::set-output name=CLUSTER_NAME::${CLUSTER_NAME}"
-          gcloud container clusters create ${CLUSTER_NAME} --zone=${{ env.GKE_ZONE }} --project=${{ env.GCP_PROJECT_ID }} --network=${{ env.GCP_NETWORK }} --machine-type=n1-standard-2 --num-nodes=2
+          gcloud container clusters create ${CLUSTER_NAME} \
+            --zone=${{ env.GKE_ZONE }} \
+            --project=${{ env.GCP_PROJECT_ID }} \
+            --network=${{ env.GCP_NETWORK }} \
+            --machine-type=n1-standard-2 \
+            --num-nodes=2
           sleep 30
 
   gke-e2e-tests:
     name: Run E2E tests
     runs-on: ubuntu-20.04
-    needs: [create-gke-cluster]
+    needs: [ create-gke-cluster ]
     strategy:
       fail-fast: false
       matrix:
@@ -68,7 +73,9 @@ jobs:
         run: |
           mkdir -p ${GITHUB_WORKSPACE}/bin
           echo "${GITHUB_WORKSPACE}/bin" >> ${GITHUB_PATH}
-          curl -L https://dl.k8s.io/release/v${{ env.KUBECTL_VERSION }}/bin/linux/amd64/kubectl -o ${GITHUB_WORKSPACE}/bin/kubectl && chmod +x ${GITHUB_WORKSPACE}/bin/kubectl
+          curl -L https://dl.k8s.io/release/v${{ env.KUBECTL_VERSION }}/bin/linux/amd64/kubectl \
+            -o ${GITHUB_WORKSPACE}/bin/kubectl
+          chmod +x ${GITHUB_WORKSPACE}/bin/kubectl
 
       - name: Set up Cloud SDK
         uses: google-github-actions/setup-gcloud@master
@@ -78,7 +85,9 @@ jobs:
           export_default_credentials: true
 
       - name: Connect to the GKE cluster
-        run: gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} --zone ${{ env.GKE_ZONE }} --project ${{ env.GCP_PROJECT_ID }}
+        run: |
+          gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} \
+            --zone ${{ env.GKE_ZONE }} --project ${{ env.GCP_PROJECT_ID }}
 
       - name: Deploy Operator to GKE
         run: |
@@ -87,13 +96,15 @@ jobs:
 
           DEPLOY_NAME=${NAME_PREFIX}controller-manager
           echo "DEPLOY_NAME=${DEPLOY_NAME}" >> $GITHUB_ENV
-          
+
           make deploy IMG=$IMG NAMESPACE=$NAMESPACE NAME_PREFIX=$NAME_PREFIX
           kubectl rollout status deployment $DEPLOY_NAME
 
       - name: Create secret
         if: matrix.edition == 'ee'
-        run: kubectl create secret generic hazelcast-license-key --namespace ${{ env.NAMESPACE }} --from-literal=license-key=${{ secrets.HZ_LICENSE_KEY }}
+        run: |
+          kubectl create secret generic hazelcast-license-key \
+            --namespace ${{ env.NAMESPACE }} --from-literal=license-key=${{ secrets.HZ_LICENSE_KEY }}
 
       - name: Run Hazelcast E2E tests at GKE
         id: e2e-test
@@ -108,13 +119,18 @@ jobs:
       - name: Clean up after Tests
         if: always()
         run: |
-          hz=$(kubectl get hazelcast -o name); [[ "$hz" != "" ]] && kubectl delete $hz --wait=false || echo "no hazelcast resources"
-          mc=$(kubectl get managementcenter -o name); [[ "$mc" != "" ]] && kubectl delete $mc --wait=false || echo "no managementcenter resources"
+          hz=$(kubectl get hazelcast -o name); [[ "$hz" != "" ]] && kubectl delete $hz --wait=false \
+            || echo "no hazelcast resources"
+          mc=$(kubectl get managementcenter -o name); [[ "$mc" != "" ]] && kubectl delete $mc --wait=false \
+            || echo "no managementcenter resources"
           if [[ ${{ steps.e2e-test.outcome }} != 'success' ]]; then
             i=0
             while ! kubectl rollout status deployment $DEPLOY_NAME; do
               kubectl rollout restart deployment $DEPLOY_NAME
-              if [[ $i == 2 ]]; then echo "Failure testing the operator, namespace $NAMESPACE requires manual clean up"; exit 1; fi
+              if [[ $i == 2 ]]; then
+                echo "Failure testing the operator, namespace $NAMESPACE requires manual clean up"
+                exit 1
+              fi
               ((i++))
             done
           fi
@@ -123,7 +139,9 @@ jobs:
           hz=$(kubectl get hazelcast -o name)
           mc=$(kubectl get managementcenter -o name)
           if [[ $hz != "" ]] || [[ $mc != "" ]]; then
-            echo "Failure deleting hazelcast and managementcenter resources, namespace $NAMESPACE requires manual clean up"; exit 1
+            echo -n "Failure deleting hazelcast and managementcenter resources, "
+            echo "namespace $NAMESPACE requires manual clean up"
+            exit 1
           fi
 
           if [[ ${{ matrix.edition }} == 'ee' ]]; then
@@ -140,7 +158,7 @@ jobs:
     name: Run E2E tests
     runs-on: ubuntu-20.04
     if: always()
-    needs: [create-gke-cluster, gke-e2e-tests]
+    needs: [ create-gke-cluster, gke-e2e-tests ]
     env:
       CLUSTER_NAME: ${{ needs.create-gke-cluster.outputs.CLUSTER_NAME }}
     steps:
diff --git a/.github/workflows/nightly-e2e-ocp.yaml b/.github/workflows/nightly-e2e-ocp.yaml
--- a/.github/workflows/nightly-e2e-ocp.yaml
+++ b/.github/workflows/nightly-e2e-ocp.yaml
@@ -3,7 +3,7 @@ on:
   workflow_dispatch:
   schedule:
     - cron: "0 9 * * *"
- 
+
 jobs:
   ocp-e2e-tests:
     name: Run e2e tests at OCP
@@ -67,13 +67,21 @@ jobs:
         if: always()
         run: |
           DEPLOY_NAME=${NAME_PREFIX}controller-manager
-          hz=$(oc get hazelcast -o name); [[ "$hz" != "" ]] && oc delete $hz --wait=false || echo "no hazelcast resources"
-          mc=$(oc get managementcenter -o name); [[ "$mc" != "" ]] && oc delete $mc --wait=false || echo "no managementcenter resources"
+
+          hz=$(oc get hazelcast -o name)
+          [[ "$hz" != "" ]] && oc delete $hz --wait=false || echo "no hazelcast resources"
+
+          mc=$(oc get managementcenter -o name)
+          [[ "$mc" != "" ]] && oc delete $mc --wait=false || echo "no managementcenter resources"
+
           if [[ ${{ steps.e2e-test.outcome }} != 'success' ]]; then
             i=0
             while ! oc rollout status deployment $DEPLOY_NAME; do
               oc rollout restart deployment $DEPLOY_NAME
-              if [[ $i == 2 ]]; then echo "Failure testing the operator, namespace $NAMESPACE requires manual clean up"; exit 1; fi
+              if [[ $i == 2 ]]; then
+                echo "Failure testing the operator, namespace $NAMESPACE requires manual clean up"
+                exit 1
+              fi
               ((i++))
             done
           fi
@@ -82,11 +90,12 @@ jobs:
           hz=$(oc get hazelcast -o name)
           mc=$(oc get managementcenter -o name)
           if [[ $hz != "" ]] || [[ $mc != "" ]]; then
-            echo "Failure deleting hazelcast and managementcenter resources, namespace $NAMESPACE requires manual clean up"; exit 1
+            echo "Failure deleting hazelcast and managementcenter resources, \
+              namespace $NAMESPACE requires manual clean up"; exit 1
           fi
 
           if [[ ${{ matrix.edition }} == 'ee' ]]; then
             oc delete secret hazelcast-license-key --wait=false
           fi
           make undeploy-keep-crd
-          oc delete project $NAMESPACE --wait=false 
+          oc delete project $NAMESPACE --wait=false
diff --git a/.github/workflows/redhat-connect-release.yaml b/.github/workflows/redhat-connect-release.yaml
--- a/.github/workflows/redhat-connect-release.yaml
+++ b/.github/workflows/redhat-connect-release.yaml
@@ -38,7 +38,7 @@ jobs:
           RHEL_IMAGE=${RHEL_REPOSITORY}:${RELEASE_VERSION}
           echo "RHEL_IMAGE=${RHEL_IMAGE}" >> $GITHUB_ENV
           echo "::set-output name=RELEASE_VERSION::${RELEASE_VERSION}"
-      
+
       - name: Generate Operator and Operator Image
         run: |
           echo "Building the operator image"
@@ -47,7 +47,7 @@ jobs:
       - name: Push Hazelcast-Platform-Operator image to RHEL scan registry
         run: |
           docker login ${SCAN_REGISTRY} -u unused -p ${RHEL_REPO_PASSWORD}
-          make docker-push IMG=${RHEL_IMAGE} 
+          make docker-push IMG=${RHEL_IMAGE}
 
       - name: Wait for Scan to Complete
         run: |
@@ -91,13 +91,20 @@ jobs:
         if: always()
         run: |
           DEPLOY_NAME=hazelcast-platform-controller-manager
-          hz=$(oc get hazelcast -o name); [[ "$hz" != "" ]] && oc delete $hz --wait=false || echo "no hazelcast resources"
-          mc=$(oc get managementcenter -o name); [[ "$mc" != "" ]] && oc delete $mc --wait=false || echo "no managementcenter resources"
+
+          hz=$(oc get hazelcast -o name)
+          [[ "$hz" != "" ]] && oc delete $hz --wait=false || echo "no hazelcast resources"
+
+          mc=$(oc get managementcenter -o name)
+          [[ "$mc" != "" ]] && oc delete $mc --wait=false || echo "no managementcenter resources"
           if [[ ${{ steps.e2e-test.outcome }} != 'success' ]]; then
             i=0
             while ! oc rollout status deployment $DEPLOY_NAME; do
               oc rollout restart deployment $DEPLOY_NAME
-              if [[ $i == 2 ]]; then echo "Failure testing the operator, namespace $NAMESPACE requires manual clean up"; exit 1; fi
+              if [[ $i == 2 ]]; then
+                echo "Failure testing the operator, namespace $NAMESPACE requires manual clean up"
+                exit 1
+              fi
               ((i++))
             done
           fi
@@ -106,13 +113,15 @@ jobs:
           hz=$(oc get hazelcast -o name)
           mc=$(oc get managementcenter -o name)
           if [[ $hz != "" ]] || [[ $mc != "" ]]; then
-            echo "Failure deleting hazelcast and managementcenter resources, namespace $NAMESPACE requires manual clean up"; exit 1
+            echo -n "Failure deleting hazelcast and managementcenter resources,"
+            echo "namespace $NAMESPACE requires manual clean up"
+            exit 1
           fi
 
-          make undeploy 
+          make undeploy
           oc delete secret hazelcast-license-key --wait=false
           oc delete secret pull-secret --wait=false
-          oc delete project $NAMESPACE --wait=false  
+          oc delete project $NAMESPACE --wait=false
 
       - name: Publish the Hazelcast-Platform-Operator image
         run: |
@@ -124,7 +133,7 @@ jobs:
           wait_for_container_publish "$PROJECT_ID" "$RELEASE_VERSION" "$RHEL_API_KEY" "$TIMEOUT_IN_MINS"
 
   redhat_bundle_release:
-    name: Create a PR in 
+    name: Create a PR in
     runs-on: ubuntu-latest
     needs: publish_image
     strategy:
@@ -132,8 +141,8 @@ jobs:
       matrix:
         include:
           - repo-name: redhat-marketplace-operators
-            repo-owner: redhat-openshift-ecosystem  
-            
+            repo-owner: redhat-openshift-ecosystem
+
           - repo-name: certified-operators
             repo-owner: redhat-openshift-ecosystem
     env:
@@ -171,7 +180,7 @@ jobs:
         run: |
           git checkout main
           git remote add upstream https://github.com/${REPO_OWNER}/${REPO_NAME}.git
-          git pull upstream main 
+          git pull upstream main
           git push origin main
 
       - name: Set Bundle Release Version
@@ -195,15 +204,16 @@ jobs:
           git commit --signoff -m "Update ${OPERATOR_NAME} to ${RELEASE_VERSION}"
           git push -u origin ${OPERATOR_NAME}-${BUNDLE_RELEASE_VERSION}-${{ github.run_id }}
 
-      - name: Create PR 
+      - name: Create PR
         working-directory: ${{ env.REPO_NAME }}
         run: |
           echo ${{ secrets.DEVOPS_GITHUB_TOKEN }} | gh auth login --with-token
-          gh pr create --title "operator ${OPERATOR_NAME} (${BUNDLE_RELEASE_VERSION})" --body "" --repo ${REPO_OWNER}/${REPO_NAME}
+          gh pr create --title "operator ${OPERATOR_NAME} \
+            (${BUNDLE_RELEASE_VERSION})" --body "" --repo ${REPO_OWNER}/${REPO_NAME}
 
   slack_notify:
     name: Slack Notify
-    needs: ['publish_image', 'redhat_bundle_release']
+    needs: [ 'publish_image', 'redhat_bundle_release' ]
     runs-on: ubuntu-latest
     if: always()
     steps:
